package com.motif.ideaforge.model.entity;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * JPA Entity for idea_analyses table
 */
@Entity
@Table(name = "idea_analyses", schema = "public")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IdeaAnalysis {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "idea_title", nullable = false, length = 255)
    private String ideaTitle;

    @Column(name = "idea_description", nullable = false, columnDefinition = "TEXT")
    private String ideaDescription;

    @Column(name = "target_market")
    private String targetMarket;

    @Column(nullable = false)
    private Integer score;

    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    private List<String> strengths;

    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    private List<String> weaknesses;

    @Type(JsonType.class)
    @Column(columnDefinition = "jsonb")
    private List<String> recommendations;

    @Column(name = "market_size", columnDefinition = "TEXT")
    private String marketSize;

    @Column(columnDefinition = "TEXT")
    private String competition;

    @Column(columnDefinition = "TEXT")
    private String viability;

    /**
     * Submission status for VC review pipeline.
     * Values: "draft" | "pending_review" | "approved_for_vc" | "rejected"
     * Requires: ALTER TABLE idea_analyses ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'draft';
     */
    @Column(name = "status", nullable = false, length = 50)
    @Builder.Default
    private String status = "draft";

    /**
     * Enriched mentor context generated on first mentor-chat request.
     * Stored as JSONB so we only generate it once (lazy, cached).
     * Requires: ALTER TABLE idea_analyses ADD COLUMN IF NOT EXISTS mentor_context JSONB;
     */
    @Type(JsonType.class)
    @Column(name = "mentor_context", columnDefinition = "jsonb")
    private Map<String, Object> mentorContext;

    /**
     * One-line summary of the idea (generated by AI).
     */
    @Column(name = "idea_summary", columnDefinition = "TEXT")
    private String ideaSummary;

    /**
     * Heuristic dimension scores (problem, market, defensibility, monetization, execution).
     * Stored as JSONB: {"problem": 18, "market": 15, ...}
     */
    @Type(JsonType.class)
    @Column(name = "heuristic_scores", columnDefinition = "jsonb")
    private Map<String, Integer> heuristicScores;

    /**
     * Investor simulation analysis (bull_case, bear_case, key_questions).
     * Stored as JSONB.
     */
    @Type(JsonType.class)
    @Column(name = "investor_analysis", columnDefinition = "jsonb")
    private Map<String, Object> investorAnalysis;

    /**
     * AI confidence score (0-100) indicating how complete the idea description was.
     */
    @Column(name = "confidence_score")
    private Integer confidenceScore;

    /**
     * Description of competitive advantages (generated by AI).
     */
    @Column(name = "competitive_advantage", columnDefinition = "TEXT")
    private String competitiveAdvantage;

    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private Instant createdAt;

    @Column(name = "updated_at")
    @UpdateTimestamp
    private Instant updatedAt;
}
